BEGIN;
ALTER TABLE users
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE ledger_entry
ADD COLUMN balance_before NUMERIC(38, 8) NOT NULL,
ADD COLUMN balance_after NUMERIC(38, 8) NOT NULL;

COMMIT;